#!/bin/bash
if [[ -f ls_cwd_content ]]
then
	rm -r ls_cwd_content
elif [[ ! -f ls_cwd_content ]]
then
	echo "total 15
drwxr-xr-x 1 ANATOLE 197121   0 Dec  6 00:20 ./
drwxr-xr-x 1 ANATOLE 197121   0 Dec  5 23:04 ../
-rwxr-xr-x 1 ANATOLE 197121  32 Dec  5 23:08 0-hello_world
-rwxr-xr-x 1 ANATOLE 197121  28 Dec  5 23:12 1-confused_smiley
-rwxr-xr-x 1 ANATOLE 197121  33 Dec  5 23:46 10-no_more_js
-rwxr-xr-x 1 ANATOLE 197121  28 Dec  5 23:23 2-hellofile
-rwxr-xr-x 1 ANATOLE 197121  45 Dec  5 23:24 3-twofiles
-rwxr-xr-x 1 ANATOLE 197121  33 Dec  5 23:34 4-lastlines
-rwxr-xr-x 1 ANATOLE 197121  33 Dec  5 23:35 5-firstlines
-rwxr-xr-x 1 ANATOLE 197121  38 Dec  5 23:44 6-third_line
-rwxr-xr-x 1 ANATOLE 197121  73 Dec  5 23:58 7-file
-rwxr-xr-x 1 ANATOLE 197121 196 Dec  6 00:19 8-cwd_state
-rwxr-xr-x 1 ANATOLE 197121  45 Dec  5 23:46 9-duplicate_last_line" > ls_cwd_content
fi
